name: Deploy to the Dev Environment

# comment
on:
  workflow_call:
    inputs:
      deploy-github-env:
        required: true
        type: string
      deploy-env:
        required: true
        type: string
      aws-region:
        required: false
        type: string
        default: "ap-southeast-2"
      account-id:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      deploy-github-env:
        description: "GitHub environment to deploy to"
        required: true
        type: environment
      aws-region:
        description: "AWS region to deploy to"
        required: false
        type: string
        default: "ap-southeast-2"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Run Tests
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Run Lint
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install Project Dependencies
        run: npm install
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk
      - name: CDK Deploy
        run: cdk deploy --all --require-approval never
