name: Trigger Dev workflows

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, labeled]
  workflow_dispatch:

jobs:
  trigger-dev-workflows:
    if: ${{ (github.head_ref != 'develop') && (github.head_ref != 'master') && (github.head_ref != 'main') }}
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      deploy-env: "dev"
      deploy-github-env: "Development"
      account-id: ${{ vars.AWS_DEV_ACCOUNT_ID }}
